/*
 * Copyright (c) 2023 - 2026 Rachit
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#version 460

#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_buffer_reference2    : enable
#extension GL_EXT_scalar_block_layout  : enable

#include "Debug/AABB/GenerateDrawCalls.h"

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    const uint AABB_INDEX_COUNT = 24;

    Constants.DebugAABBDrawCalls.drawCalls[0] = GenerateDrawCall(AABB_INDEX_COUNT, Constants.CulledOpaqueDrawCalls.count);
    Constants.DebugAABBDrawCalls.drawCalls[1] = GenerateDrawCall(AABB_INDEX_COUNT, Constants.CulledOpaqueDoubleSidedDrawCalls.count);
    Constants.DebugAABBDrawCalls.drawCalls[2] = GenerateDrawCall(AABB_INDEX_COUNT, Constants.CulledAlphaMaskedDrawCalls.count);
    Constants.DebugAABBDrawCalls.drawCalls[3] = GenerateDrawCall(AABB_INDEX_COUNT, Constants.CulledAlphaMaskedDoubleSidedDrawCalls.count);
}