/*
 * Copyright (c) 2023 - 2026 Rachit
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// References Used:
// Ray Tracing Gems v1.9 (Unofficial)
// Chapter 25: Hybrid Rendering for Real-Time Ray Tracing
// 25.2.1: Shadows

#version 460 core

#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_buffer_reference2    : enable
#extension GL_EXT_scalar_block_layout  : enable
#extension GL_EXT_ray_tracing          : enable

#include "MegaSet.glsl"
#include "Encoding.glsl"
#include "Constants.glsl"
#include "Math.glsl"
#include "Random.glsl"
#include "Sampling.glsl"
#include "Shadows/ShadowRT.h"

layout(location = 0) rayPayloadEXT float shadowAmount;

void main()
{
    vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5f);
    vec2 uv          = pixelCenter / vec2(gl_LaunchSizeEXT.xy);

    float depth = texture(sampler2D(Textures[Constants.SceneDepthIndex], Samplers[Constants.GBufferSamplerIndex]), uv).r;

    if (depth == 0.0f)
    {
        imageStore(Images[Constants.OutputImage], ivec2(gl_LaunchIDEXT.xy), vec4(1.0f, 0.0f, 0.0f, 0.0f));

        return;
    }

    uint pixelIndex  = gl_LaunchSizeEXT.x * gl_LaunchIDEXT.y + gl_LaunchIDEXT.x;
    uint frameIndex  = uint(Constants.Scene.frameIndex);
    uint haltonIndex = Constants.TemporalPhaseCount * pixelIndex + frameIndex;

    uint rngState = pixelIndex ^ (20232026u * frameIndex);
         rngState = PCG(rngState);

    float jitter0 = Random(rngState);
    float jitter1 = Random(rngState);

    vec3 worldPosition = GetWorldPosition(Constants.Scene.currentMatrices, uv, depth);

    vec4 gNormal = texture(sampler2D(Textures[Constants.GNormalIndex], Samplers[Constants.GBufferSamplerIndex]), uv);
    vec3 normal  = UnpackNormalFromGBuffer(gNormal.rg);

    vec3 direction = normalize(-Constants.Scene.Sun.light.direction);
    vec3 tangent   = vec3(0.0f);
    vec3 bitangent = vec3(0.0f);

    BuildOrthonormalBasis(direction, tangent, bitangent);

    float cosTheta = saturate(dot(normal, direction));
    float bias     = RT_SHADOW_MIN_BIAS * TanArcCos(cosTheta);
    bias           = clamp(bias, 0.0f, RT_SHADOW_MAX_BIAS);

    // TODO: Consider a better self-intersection prevention method
    vec3 origin = worldPosition + normal * bias;

    const uint  rayFlags        = gl_RayFlagsSkipClosestHitShaderEXT | gl_RayFlagsTerminateOnFirstHitEXT;
    const uint  cullMask        = 0xFFu;
    const float tmin            = 0.001f;
    const float tmax            = 1e27f;
    const uint  sbtRecordOffset = 0u;
    const uint  sbtRecordSize   = 0u;
    const uint  missIndex       = 0u;
    const int   payloadLocation = 0;

    float totalShadow = 0.0f;

    for (uint i = 0; i < RT_SHADOW_RAY_COUNT; ++i)
    {
        uint  sampleIndex  = RT_SHADOW_RAY_COUNT * haltonIndex + i;
        float random0      = fract(HaltonBase2(sampleIndex) + jitter0);
        float random1      = fract(Halton(sampleIndex, 3u)  + jitter1);
        vec2  randomPoint  = vec2(random0, random1);

        vec3 randomDirection = UniformSampleCone(randomPoint, RT_COS_SUN_ANGULAR_RADIUS);
        vec3 rayDirection    = normalize(randomDirection.x * tangent + randomDirection.y * bitangent + randomDirection.z * direction);

        // Assume that the ray hits something, i.e, the point is in shadow
        shadowAmount = 1.0f;

        traceRayEXT
        (
            accelerationStructureEXT(Constants.TLAS),
            rayFlags,
            cullMask,
            sbtRecordOffset,
            sbtRecordSize,
            missIndex,
            origin,
            tmin,
            rayDirection,
            tmax,
            payloadLocation
        );

        totalShadow += shadowAmount;
    }

    totalShadow /= float(RT_SHADOW_RAY_COUNT);

    imageStore(Images[Constants.OutputImage], ivec2(gl_LaunchIDEXT.xy), vec4(1.0f - totalShadow, 0.0f, 0.0f, 0.0f));
}