/*
 * Copyright (c) 2023 - 2025 Rachit
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// https://ar5iv.labs.arxiv.org/html/2301.11376
// Reference implementation #1: https://github.com/bevyengine/bevy/blob/main/crates/bevy_pbr/src/ssao/ssao.wgsl
// Reference implementation #2: https://cybereality.com/screen-space-indirect-lighting-with-visibility-bitmask-improvement-to-gtao-ssao-real-time-ambient-occlusion-algorithm-glsl-shader-implementation/
// Reference implementation #3: https://cdrinmatane.github.io/posts/ssaovb-code/

#version 460

#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_buffer_reference2    : enable
#extension GL_EXT_scalar_block_layout  : enable

#include "Math.glsl"
#include "Constants.glsl"
#include "MegaSet.glsl"
#include "Packing.glsl"
#include "AO/VBAO/VBAO.h"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

vec2  LoadNoise(ivec2 pixelCoord);
float CalculateNeighboringDepthDifferences(ivec2 pixelCoord, vec2 viewportSize);
vec3  LoadViewSpaceNormal(vec2 uv);
vec3  ReconstructViewSpacePosition(vec2 uv, float depth);
vec3  LoadAndReconstructViewSpacePosition(vec2 uv, float mipLevel);
uint  UpdateSectors(float minHorizon, float maxHorizon, uint globalOccludedBitfield);

void main()
{
    ivec2 pixelCoord = ivec2(gl_GlobalInvocationID.xy);

    vec2 viewportSize = vec2(textureSize(sampler2D(Textures[Constants.PreFilterDepthIndex], Samplers[Constants.PointSamplerIndex]), 0));
    vec2 aspect       = viewportSize.yx / viewportSize.x;
    vec2 texelSize    = 1.0f / viewportSize;
    vec2 pixelCenter  = vec2(pixelCoord) + vec2(0.5f);
    vec2 uv           = pixelCenter * texelSize;

    float depthMipLevels = float(textureQueryLevels(sampler2D(Textures[Constants.PreFilterDepthIndex], Samplers[Constants.PointSamplerIndex])));

    float depth  = CalculateNeighboringDepthDifferences(pixelCoord, viewportSize);
          depth += 0.00001f; // Add a small value to avoid depth precision issues

    vec3 position = ReconstructViewSpacePosition(uv, depth);
    vec3 normal   = LoadViewSpaceNormal(uv);
    vec2 noise    = LoadNoise(pixelCoord);

    vec3  viewVector  = normalize(-position);
    float sampleScale = (-VBAO_EFFECT_RADIUS * Constants.Scene.currentMatrices.projection[0][0]) / position.z;

    float visibility = 0.0f;
    float correction = 0.0f;

    for (uint slice = 0; slice < VBAO_SLICE_COUNT; ++slice)
    {
        float sliceK = (slice + noise.x) / VBAO_SLICE_COUNT;

        float phi    = sliceK * TWO_PI;
        float cosPhi = cos(phi);
        float sinPhi = sin(phi);

        vec3  direction             = vec3(cosPhi, sinPhi, 0.0f);
        vec3  orthoDirection        = direction - (dot(direction, viewVector) * viewVector);
        vec3  axis                  = normalize(cross(direction, viewVector));
        vec3  projectedNormal       = normal - dot(normal, axis) * axis;
        float projectedNormalLength = max(length(projectedNormal), 1e-5f);

        float signNorm = sign(dot(orthoDirection, projectedNormal));
        float cosNorm  = clamp(dot(projectedNormal, viewVector) / projectedNormalLength, -1.0f, 1.0f);
        float N        = signNorm * acos(cosNorm);

        uint globalOccludedBitfield = 0u;

        // Coordinate system weirdness, flip omega.y
        vec2 omega = vec2(cosPhi, -sinPhi);
        // Account for the aspect ratio, thanks cybereality!
        vec2 sampleMul = omega * sampleScale * aspect;

        for (uint sampleIndex = 0; sampleIndex < VBAO_SAMPLE_COUNT; ++sampleIndex)
        {
            float sampleNoise = (slice * VBAO_SAMPLE_COUNT + sampleIndex) * 0.6180339887498948482f;
                  sampleNoise = fract(noise.y + sampleNoise);

            float s = (sampleIndex + sampleNoise) / VBAO_SAMPLE_COUNT;

            vec2 sampleOffset = s * sampleMul;
            vec2 sampleUV     = uv - sampleOffset;

            float sampleMipLevel = clamp(log2(length(sampleOffset * viewportSize)) - VBAO_DEPTH_MIP_SAMPLING_OFFSET, 0.0f, depthMipLevels - 1.0f);

            vec3 samplePosition   = LoadAndReconstructViewSpacePosition(sampleUV, sampleMipLevel);
            vec3 sampleDifference = samplePosition - position;

            vec2 frontBackHorizon = vec2(0.0f);

            frontBackHorizon.x = dot(normalize(sampleDifference), viewVector);
            frontBackHorizon.y = dot(normalize(sampleDifference - viewVector * Constants.Thickness), viewVector);

            frontBackHorizon = clamp(frontBackHorizon, -1.0f, 1.0f);
            frontBackHorizon = acos(frontBackHorizon);
            frontBackHorizon = saturate((frontBackHorizon + N + HALF_PI) / PI);

            float minHorizon = min(frontBackHorizon.x, frontBackHorizon.y);
            float maxHorizon = max(frontBackHorizon.x, frontBackHorizon.y);

            globalOccludedBitfield = UpdateSectors(minHorizon, maxHorizon, globalOccludedBitfield);
        }

        visibility += 1.0f - float(bitCount(globalOccludedBitfield)) / float(VBAO_SECTOR_COUNT);

        // Arycama's Correction
        correction += projectedNormalLength * (N * sin(N) + cosNorm);
    }

    visibility /= max(correction, 1e-5f);

    // Disallow total occlusion
    visibility = clamp(visibility, 0.03f, 1.0f);

    imageStore(Images[Constants.OutNoisyAOIndex], pixelCoord, vec4(visibility, 0.0f, 0.0f, 0.0f));
}

vec2 LoadNoise(ivec2 pixelCoord)
{
    // Hilbert curve driving R2 (see https://www.shadertoy.com/view/3tB3z3)
    uint index  = uint(texelFetch(usampler2D(UTextures[Constants.HilbertLUTIndex], Samplers[Constants.PointSamplerIndex]), pixelCoord % int(VBAO_HILBERT_WIDTH), 0).x);
         index += 288 * Constants.TemporalIndex;

    // R2 sequence - see http://extremelearning.com.au/unreasonable-effectiveness-of-quasirandom-sequences/
    return vec2(fract(0.5f + float(index) * vec2(0.75487766624669276005f, 0.5698402909980532659114f)));
}

float CalculateNeighboringDepthDifferences(ivec2 pixelCoord, vec2 viewportSize)
{
    vec2 uv = vec2(pixelCoord) / viewportSize;

    vec4 depthsUpperLeft   = textureGather      (sampler2D(Textures[Constants.PreFilterDepthIndex], Samplers[Constants.PointSamplerIndex]), uv             );
    vec4 depthsBottomRight = textureGatherOffset(sampler2D(Textures[Constants.PreFilterDepthIndex], Samplers[Constants.PointSamplerIndex]), uv, ivec2(1, 1));
    
    float depthCenter = depthsUpperLeft.y;
    float depthLeft   = depthsUpperLeft.x;
    float depthTop    = depthsUpperLeft.z;
    float depthBottom = depthsBottomRight.x;
    float depthRight  = depthsBottomRight.z;

    vec4 edgeInfo = vec4(depthLeft, depthRight, depthTop, depthBottom) - depthCenter;

    float slopeLeftRight = (edgeInfo.y - edgeInfo.x) * 0.5f;
    float slopeTopBottom = (edgeInfo.w - edgeInfo.z) * 0.5f;
    
    vec4 edgeInfoSlopeAdjusted = edgeInfo + vec4(slopeLeftRight, -slopeLeftRight, slopeTopBottom, -slopeTopBottom);

    edgeInfo = min(abs(edgeInfo), abs(edgeInfoSlopeAdjusted));
    
    float bias  = 0.25f;
    float scale = depthCenter * 0.011f;

    edgeInfo = saturate((1.0f + bias) - edgeInfo / scale);

    imageStore(UImages[Constants.OutDepthDifferencesIndex], pixelCoord, uvec4(packUnorm4x8(edgeInfo), 0u, 0u, 0u));
    
    return depthCenter;
}

vec3 LoadViewSpaceNormal(vec2 uv)
{
    vec4 gNormal = texture(sampler2D(Textures[Constants.GNormalIndex], Samplers[Constants.PointSamplerIndex]), uv);

    vec3 normal = UnpackNormal(gNormal.rg);
         normal = mat3(Constants.Scene.currentMatrices.view) * normal;
         normal = normalize(normal);

    return normal;
}

vec3 ReconstructViewSpacePosition(vec2 uv, float depth)
{
    return GetViewPosition(Constants.Scene.currentMatrices, uv, depth);
}

vec3 LoadAndReconstructViewSpacePosition(vec2 uv, float mipLevel)
{
    float depth = textureLod(sampler2D(Textures[Constants.PreFilterDepthIndex], Samplers[Constants.LinearSamplerIndex]), uv, mipLevel).r;

    return ReconstructViewSpacePosition(uv, depth);
}

uint UpdateSectors(float minHorizon, float maxHorizon, uint globalOccludedBitfield)
{
    uint startHorizon = uint(minHorizon * float(VBAO_SECTOR_COUNT));
    uint angleHorizon = uint(ceil((maxHorizon - minHorizon) * float(VBAO_SECTOR_COUNT)));

    angleHorizon = min(angleHorizon, VBAO_SECTOR_COUNT);

    uint angleHorizonBitfield    = angleHorizon > 0u ? (0xFFFFFFFFu >> (VBAO_SECTOR_COUNT - angleHorizon)) : 0u;
    uint currentOccludedBitfield = angleHorizonBitfield << startHorizon;

    return globalOccludedBitfield | currentOccludedBitfield;
}